server:
  port: 8889
spring:
  application:
    name: service-ucenter
  profiles:
    active: dev #  dev? test?prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:  # nacos服务地址
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 1800000
      pool:
        max-active: 20
        max-wait: -1   #最大阻塞等待时间(负数表示没限制)
        max-idle: 8
        min-idle: 0
    host: 127.0.0.1

logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/zar/service_ucenter/mapper/xml/*.xml



